FROM openjdk:11

WORKDIR /usr/local/app

ADD SimpleService-0.0.1-SNAPSHOT.jar app.jar

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && java -jar app.jar
